version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "81:80/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'Asia/Jakarta'
      WEBPASSWORD: 'password'
      # your ip address
      # SERVERIP: ''
    volumes:
      - './apps/pihole/:/etc/pihole/'
      - './apps/dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
